language: bash
sudo: required
env:
  matrix:
  - DEPLOY_ENVIRONMENT=staging
services:
- docker
script:
- |
  if [ "${DEPLOY_ENVIRONMENT}" != "" ] && [ "${TRAVIS_PULL_REQUEST}" == "false" ] && [ "${TRAVIS_BRANCH}" == "master" ] &&\
     [ "${TRAVIS_COMMIT_MESSAGE}" != "" ] && ! echo "${TRAVIS_COMMIT_MESSAGE}" | grep -- --no-deploy && [ "${TRAVIS_COMMIT}" != "" ]
  then
      openssl aes-256-cbc -K $encrypted_4cd4da97f821_key -iv $encrypted_4cd4da97f821_iv -in k8s-ops-secret.json.enc -out secret-k8s-ops.json -d
      charts/sk8s-ops/run_docker_ops.sh "${DEPLOY_ENVIRONMENT}" "
           cd /ops
           ! ./helm_upgrade.sh \
                 && echo 'failed helm upgrade' && exit 1
           exit 0
      " "orihoch/sk8s-ops" "OriHoch/sk8s" "master"
  fi
