{{ if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  default.conf: |
    server {
      listen 80;
      server_name _;

      include /etc/nginx/conf.d/healthcheck.inc;

      {{ if .Values.enableAdminer }}
      location /adminer {
        proxy_pass http://adminer:8080;
        include /etc/nginx/conf.d/restricted.inc;
      }
      {{ end }}
    }

  healthcheck.inc: |
    location = / {
        return 200 'it works!';
        add_header Content-Type text/plain;
    }

  restricted.inc: |
    {{ if .Values.htpasswdSecretName }}
    auth_basic "Restricted Content";
    auth_basic_user_file /etc/nginx/htpasswd/secret-nginx-htpasswd;
    {{ end }}
{{ end }}
