{{ if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: traefik
spec:
  ports:
  - {name: '80', port: 80}
  - {name: '443', port: 443}
  selector:
    app: traefik
  type: LoadBalancer
  {{ if .Values.loadBalancerIP }}
  loadBalancerIP: {{ .Values.loadBalancerIP | quote }}
  {{ end }}
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: traefik
spec:
  # don't increase the replicas unless you switch to consul storage of acme certificates
  replicas: 1
  template:
    metadata:
      labels:
        app: traefik
      annotations:
        # update the pod on traefik configuration changes
        checksum/config: {{ include (print $.Template.BasePath "/traefik-etc.yaml") . | sha256sum }}
    spec:
      {{ if .Values.nodeHostName }}
      nodeSelector:
        kubernetes.io/hostname: {{ .Values.nodeHostName | quote }}
      {{ end }}{{ if .Values.nodePool }}
      nodeSelector:
        cloud.google.com/gke-nodepool: {{ .Values.nodePool | quote }}
      {{ end }}
      initContainers:
      # initops container - copies the acme data from last backup before starting up the pod
      - name: initops
        image: gcr.io/uumpa-public/sk8s-google-storage-sync:v0.0.2
        resources: {"requests": {"cpu": "1m", "memory": "2Mi"}}
        env:
        - name: CLOUDSDK_CORE_PROJECT
          value: bh-org-01
        - name: GS_BUCKET_NAME
          value: mojp-k8s-backups
        command:
        - bash
        - "-c"
        - |
          source ~/.bashrc;
          gcloud config set project "${CLOUDSDK_CORE_PROJECT}"
          ! gsutil -m rsync -x '^done|synced$' -r "gs://${GS_BUCKET_NAME}/{{ .Values.global.environmentName }}/traefik-acme/latest/" /traefik-acme/ \
            && echo "failed to get traefik acme details from backup, continuing anyway, traefik will create new certificates (hopefully..)"
          chmod -R 600 /traefik-acme
        volumeMounts:
        - name: k8s-ops
          mountPath: /k8s-ops
          readOnly: true
        - name: traefik-acme
          mountPath: /traefik-acme
      containers:
      - name: ops
        image: gcr.io/uumpa-public/sk8s-google-storage-sync:v0.0.2
        resources: {"requests": {"cpu": "1m", "memory": "2Mi"}}
        env:
        - name: CLOUDSDK_CORE_PROJECT
          value: bh-org-01
        - name: GS_BUCKET_NAME
          value: mojp-k8s-backups
        command:
        - bash
        - "-c"
        - |
          source ~/.bashrc;
          gcloud config set project "${CLOUDSDK_CORE_PROJECT}"
          echo "sleeping for 4 minutes before making the first backup to allow traefik time to issue certificates"
          sleep 240
          echo "making daily backups"
          LATEST_BACKUP="gs://${GS_BUCKET_NAME}/{{ .Values.global.environmentName }}/traefik-acme/latest/"
          echo "LATEST_BACKUP=${LATEST_BACKUP}"
          while true; do
            HISTORY_BACKUP="gs://${GS_BUCKET_NAME}/{{ .Values.global.environmentName }}/traefik-acme/`date +%Y-%m-%d-%H-%M`/"
            echo "HISTORY_BACKUP=${HISTORY_BACKUP}"
            ! gsutil -m rsync -x '^done|synced$' -r /traefik-acme/ gs://${GS_BUCKET_NAME}/{{ .Values.global.environmentName }}/traefik-acme/latest/ \
              && echo "failed to sync latest backup" && exit 1
            ! gsutil -m rsync -x '^done|synced$' -r /traefik-acme/ "${HISTORY_BACKUP}" \
              && echo "failed to sync ${HISTORY_BACKUP}" && exit 1
            echo "sleeping for 1 day"
            sleep 86400
          done
        volumeMounts:
        - name: k8s-ops
          mountPath: /k8s-ops
          readOnly: true
        - name: traefik-acme
          mountPath: /traefik-acme
      - name: traefik
        image: traefik
        ports:
        - {containerPort: 80}
        - {containerPort: 443}
        resources:
          requests: {cpu: 20m}
        volumeMounts:
        - name: etc-traefik
          mountPath: /etc-traefik
        - name: traefik-acme
          mountPath: /traefik-acme
        args:
        - "--configFile=/etc-traefik/traefik.toml"

        {{ if .Values.traefik.CLOUDFLARE_EMAIL }}
        # to use cloudflare for dns certificate challenge you should also set acme.dnsProvider = cloudflare
        # see https://docs.traefik.io/configuration/acme/
        env:
        - name: CLOUDFLARE_EMAIL
          value: {{ .Values.CLOUDFLARE_EMAIL | quote }}
        - name: CLOUDFLARE_API_KEY
          valueFrom:
            secretKeyRef:
              name: cloudflare
              key: CLOUDFLARE_API_KEY
        {{ end }}
      volumes:
      - name: etc-traefik
        configMap:
          name: etc-traefik
      - name: traefik-acme
        emptyDir: {}
      - name: k8s-ops
        secret:
          secretName: ops
{{ end }}
