{{ if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: etc-traefik
data:
  traefik.toml: |
    # https://docs.traefik.io/configuration/commons/

    {{ if .Values.global.debug }}
    debug = true
    {{ end }}

    defaultEntryPoints = ["http", "https"]
    
    [entryPoints]
        [entryPoints.http]
          address = ":80"
            [entryPoints.http.redirect]
              entryPoint = "https"
        
        [entryPoints.https]
          address = ":443"
            [entryPoints.https.tls]

    {{ if .Values.traefik.acmeEmail }}
    # let's encrypt automatic ssl certificate issue and renewal
    [acme]
      email = {{ .Values.acmeEmail | quote }}
      {{ if .Values.traefik.dnsProvider }}
      dnsProvider = {{ .Values.traefik.dnsProvider | quote }}
      {{ end }}
      storage = "/traefic-acme/acme.json"
      entryPoint = "https"
      [[acme.domains]]
        main = "{{ .Values.rootDomain }}"
    {{ end }}

    [file]
    
    [backends]
      {{ if .Values.enableNginx }}
      [backends.nginx]
        [backends.nginx.servers.server1]
          url = "http://nginx:80"
      {{ end }}

    [frontends]
      {{ if .Values.enableNginx }}
      [frontends.default]
        backend="nginx"
        passHostHeader = true
      {{ end }}

{{ end }}
