{{ if .Values.enabled }}{{ if .Values.dbBackupJob }}
apiVersion: batch/v1
kind: Job
#apiVersion: batch/v1beta1
#kind: CronJob
metadata:
  name: volunteersdb-backup
spec:
#  schedule: "@daily"
#  concurrencyPolicy: Forbid
#  jobTemplate:
#    spec:
  template:
    metadata:
      name: volunteersdb-backup
    spec:
      containers:
      - name: ops
        image: orihoch/sk8s-ops:mongo@sha256:17b06a6c3aa4e56144438a510e5f4051725516321703374fb53aadbf0ed9904a
        resources:
          requests:
            cpu: "0.01"
            memory: "10Mi"
        command:
        - bash
        - "-c"
        - |
          source ~/.bashrc
          EXPORT_URL="gs://{{ .Values.global.projectName }}-k8s-backups/volunteersdb-{{ .Values.global.environmentName }}-mongodump-`date +%Y-%m-%d-%H-%M`.tar.gz"
          echo "EXPORT_URL=${EXPORT_URL}"
          gcloud config set project "{{ .Values.global.googleProjectId }}" &&\
          mongodump -hvolunteersdb -omongodump -dvolunteers &&\
          tar -czvf mongodump.tar.gz mongodump &&\
          ls -lah mongodump.tar.gz &&\
          gsutil cp mongodump.tar.gz "${EXPORT_URL}" &&\
          echo "Great Success!"
        volumeMounts:
        - name: k8s-ops
          mountPath: /k8s-ops
          readOnly: true
      volumes:
      - name: k8s-ops
        secret:
          secretName: ops
      restartPolicy: Never
{{ end }}{{ end }}
